#!/usr/bin/env python3
from sys import argv
from os import path, listdir
import json

notes_file = "notes.json"

def initialise_notes() -> dict:
    return {"groups": [], "other": []}

def print_notes(notes: dict) -> None:
    if notes["groups"] == [] and notes["other"] == []:
        print("No notes to show.")
        return
    
    for i, group in enumerate(notes["groups"]):
        print(f"[{i + 1}]: {group['name']}")
        for j, note in enumerate(group["notes"]):
            print(f"\t[{i + 1}.{j + 1}]: " + note)
    
    if notes["other"] != []:
        print("\nOther notes:")
        for i, note in enumerate(notes["other"]):
            print(f"\t[{len(notes['groups']) + 1}.{i + 1}]: " + note)

 
def main() -> None:
    note_data = {}
    script_dir = path.dirname(path.realpath(__file__))
    if notes_file not in listdir(script_dir):
        print("'notes.json' not found, initialising Note...")
        open(notes_file, 'x')
        note_data = initialise_notes()
    else:
        with open(path.join(script_dir, notes_file), 'r') as f:
            note_data = json.load(f)
    
    print_notes(note_data)
    notes_json = json.dumps(note_data, indent=2)
    # TODO: TACTOU maybe fix
    with open(path.join(script_dir, notes_file), 'w') as f:
        f.write(notes_json)



if __name__ == "__main__":
    try:
        main()
    except Exception as e:
        print(str(e))
