#!/usr/bin/env python3

from sys import argv
from os import path, listdir
import json

notes_file = "notes.json"

def initialise_notes() -> dict:
    return {"groups": [], "other": []}

def print_notes(notes: dict) -> None:
    if notes["groups"] == [] and notes["other"] == []:
        print("No notes to show.")
        return
    
    for i, group in enumerate(notes["groups"]):
        print(f"[{i + 1}]: {group['name']}")
        for j, note in enumerate(group["notes"]):
            print(f"\t[{i + 1}.{j + 1}]: " + note)
    
    if notes["other"] != []:
        print("\nOther notes:")
        for i, note in enumerate(notes["other"]):
            print(f"\t[{len(notes['groups']) + 1}.{i + 1}]: " + note)

 
def main() -> None:
    note_data = {}
    script_dir = path.dirname(path.realpath(__file__))
    if notes_file not in listdir(script_dir):
        print("'notes.json' not found, initialising Note...")
        open(notes_file, 'x')
        note_data = initialise_notes()
    else:
        with open(path.join(script_dir, notes_file), 'r') as f:
            note_data = json.load(f)
    
    if len(argv) == 1:
        print_notes(note_data)
        return
    
    if argv[1] == "group":
        if len(argv) == 2:
            raise Exception("No name for group added.")
        
        note_data["groups"].append(" ".join(argv[2:]))
    
    elif isinstance(argv[1], float):
        index = argv[1].split('.')
        if len(index) != 2:
            raise Exception("Index contains too few or too many things.")
        # TODO: fix for other notes, +1 gone and separate case for other
        if index[0].startswith('-'):
            if int(index[0][1:]) < 1 or int(index[0]) > len(note_data["groups"]) + 1:
                raise Exception("No valid index for group.")
            
            if int(index[1]) < 1 or int(index[1]) > len(note_data["groups"][int(index[1]) - 1]):
                raise Exception("No valid index for note.")
            
            note_data["groups"][int(index[0][1:]) - 1].pop([int(index[1])])
        
        else:
            ...
            
            




    notes_json = json.dumps(note_data, indent=2)
    # TODO: TACTOU maybe fix
    with open(path.join(script_dir, notes_file), 'w') as f:
        f.write(notes_json)



if __name__ == "__main__":
    try:
        main()
    except Exception as e:
        print(str(e))
